"""Catálogo mestre das 6 Suítes de Extensões da plataforma Eltanix Coder IDE."""

from __future__ import annotations

from typing import Literal

ExtensionCategory = Literal[
    "Frontend & Visual",
    "IA & Web Scraping",
    "Bancos & RAG",
    "Segurança & Auditoria",
    "APIs & Testes",
    "Segundo Cérebro & Arquitetura",
    "LSP & Linguagens",
    "DevOps & Containers",
    "Produtividade",
]


class ExtensionDefinition:
    def __init__(
        self,
        id: str,
        name: str,
        publisher: str,
        version: str,
        description: str,
        category: ExtensionCategory,
        icon: str,
        installed: bool = True,
        active: bool = True,
        is_recommended: bool = True,
        downloads: str = "100K+",
        rating: float = 4.9,
        upstream_id: str | None = None,
        repository_url: str | None = None,
        features: list[str] | None = None,
    ) -> None:
        self.id = id
        self.name = name
        self.publisher = publisher
        self.version = version
        self.description = description
        self.category = category
        self.icon = icon
        self.installed = installed
        self.active = active
        self.is_recommended = is_recommended
        self.downloads = downloads
        self.rating = rating
        self.upstream_id = upstream_id or id
        self.repository_url = repository_url
        self.features = features or []

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "publisher": self.publisher,
            "version": self.version,
            "description": self.description,
            "category": self.category,
            "icon": self.icon,
            "installed": self.installed,
            "active": self.active,
            "isRecommended": self.is_recommended,
            "downloads": self.downloads,
            "rating": self.rating,
            "upstream_id": self.upstream_id,
            "repository_url": self.repository_url,
            "features": self.features,
        }


# Catálogo com as 6 Suítes Completas de Extensões
MASTER_EXTENSIONS_CATALOG: list[ExtensionDefinition] = [
    # ── SUÍTE 1: FRONTEND, DESIGN SYSTEM & PROTOTIPAGEM RÁPIDA ──────────────────
    ExtensionDefinition(
        id="eltanix.shadcn-radix-studio",
        name="Shadcn UI & Radix Component Registry",
        publisher="shadcn",
        version="1.4.0",
        description="Navegador e injetor interativo de componentes acessíveis (Dialogs, Dropdowns, Sheets, Toasts, Accordions).",
        category="Frontend & Visual",
        icon="🎨",
        downloads="1.2M",
        rating=4.98,
        upstream_id="shadcn.shadcn-ui",
        repository_url="https://github.com/shadcn-ui/ui",
        features=[
            "Injeção de componentes com 1 clique",
            "Suporte a Tailwind CSS e variáveis CSS",
            "Acessibilidade WCAG AA via Radix Primitives",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.daisyui-theme-explorer",
        name="DaisyUI & Tailwind Theme Explorer",
        publisher="saadeghi",
        version="4.12.10",
        description="Seletor dinâmico de 28 temas Tailwind com visualização instantânea de cores, botões e cards.",
        category="Frontend & Visual",
        icon="🌼",
        downloads="850K",
        rating=4.92,
        upstream_id="saadeghi.daisyui",
        repository_url="https://github.com/saadeghi/daisyui",
        features=[
            "28 temas prontos (Dark, Cyberpunk, Forest, Business, Nord, Corporate)",
            "Geração de tailwind.config com 1 clique",
            "Preview interativo em tempo real",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.lucide-tabler-icons",
        name="Lucide & Tabler Icon Studio",
        publisher="lucide",
        version="0.460.0",
        description="Paleta de busca e inserção de mais de 1.400 ícones vetoriais SVG para React, Vue e Jinja/HTML.",
        category="Frontend & Visual",
        icon="✨",
        downloads="2.4M",
        rating=4.99,
        upstream_id="lucide.lucide",
        repository_url="https://github.com/lucide-icons/lucide",
        features=[
            "Busca instantânea por tags e semântica",
            "Inserção como JSX (<LucideIcon />) ou HTML/SVG",
            "CDN de carregamento rápido para templates Flask/FastAPI",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.live-server-templates",
        name="Live Server & Hot-Reload para Templates",
        publisher="ritwickdey",
        version="5.7.9",
        description="Servidor de hot-reload automático para páginas Flask, FastAPI, Jinja e Alpine.js conectado ao navegador interno.",
        category="Frontend & Visual",
        icon="⚡",
        downloads="35M",
        rating=4.88,
        upstream_id="ritwickdey.LiveServer",
        repository_url="https://github.com/ritwickdey/vscode-live-server",
        features=[
            "Recarregamento instantâneo via WebSocket",
            "Integração nativa com o Navegador Interno Fullscreen",
            "Suporte a templates Jinja e Alpine.js",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.chart-dataviz-studio",
        name="Chart.js & ApexCharts Data Viz Studio",
        publisher="chartjs",
        version="4.4.4",
        description="Visualizador e gerador de snippets para gráficos interativos de dashboards (linhas, barras, roscas e séries temporais).",
        category="Frontend & Visual",
        icon="📊",
        downloads="420K",
        rating=4.91,
        upstream_id="chartjs.chartjs",
        repository_url="https://github.com/chartjs/Chart.js",
        features=[
            "Geração de snippets prontos para React e HTML",
            "Paletas coordenadas com o tema do sistema",
            "Preview dinâmico com dados de teste",
        ],
    ),
    # ── SUÍTE 2: IA, WEB SCRAPING & CONECTORES DE DADOS (FIRECRAWL & MCP) ────────
    ExtensionDefinition(
        id="eltanix.firecrawl-workflow-builder",
        name="Firecrawl Visual Workflow Builder (Open Agent Builder)",
        publisher="firecrawl",
        version="1.2.0",
        description="Construtor visual drag-and-drop para pipelines de web scraping, crawling e extração estruturada de dados.",
        category="IA & Web Scraping",
        icon="🔥",
        downloads="180K",
        rating=4.95,
        upstream_id="firecrawl.open-agent-builder",
        repository_url="https://github.com/firecrawl/open-agent-builder",
        features=[
            "Montagem visual de nós de scraping e RAG",
            "Execução em tempo real no sandbox",
            "Proteção Anti-SSRF integrada",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.llm-data-connectors",
        name="LLM Data Connectors (Firecrawl Connectors)",
        publisher="firecrawl",
        version="1.1.0",
        description="Conectores de dados prontos para ingestão contínua de GitHub Issues, Notion, Jira, Slack e Google Drive no RAG.",
        category="IA & Web Scraping",
        icon="🔌",
        downloads="95K",
        rating=4.89,
        upstream_id="firecrawl.data-connectors",
        repository_url="https://github.com/firecrawl/data-connectors",
        features=[
            "Ingestão automática no pgvector",
            "Divisão de chunks por símbolo e semântica",
            "Sincronização incremental periódica",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.mcp-marketplace-scanner",
        name="MCP Marketplace & Security Inspector",
        publisher="eltanix",
        version="2.0.0",
        description="Gerenciador de servidores Model Context Protocol (MCP) com varredura contínua de segurança contra Tool Poisoning.",
        category="IA & Web Scraping",
        icon="🛡️",
        downloads="310K",
        rating=4.96,
        upstream_id="eltanix.mcp-inspector",
        repository_url="https://github.com/cisco-open/cisco-mcp-scanner",
        features=[
            "Scan automatizado via cisco-mcp-scanner",
            "Conexão com servidores stdio e Streamable HTTP",
            "Classificação de risco de ferramentas (READ, WRITE, EXEC)",
        ],
    ),
    # ── SUÍTE 3: BANCOS DE DADOS, VETORES & CACHE ──────────────────────────────
    ExtensionDefinition(
        id="eltanix.pgvector-semantic-studio",
        name="pgvector & Semantic RAG Studio",
        publisher="postgres",
        version="2.5.0",
        description="Inspetor de vetores de alta dimensão, busca por similaridade cosseno e visualização do ranking híbrido RRF.",
        category="Bancos & RAG",
        icon="🧠",
        downloads="450K",
        rating=4.94,
        upstream_id="pgvector.pgvector-studio",
        repository_url="https://github.com/pgvector/pgvector",
        features=[
            "Explorador de embeddings em 1536 dimensões",
            "Simulador de consultas híbridas (Full-text + Vetores)",
            "Visualização de scores Reciprocal Rank Fusion (RRF)",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.redis-commander",
        name="Redis Commander & Cache Inspector",
        publisher="redis",
        version="3.1.0",
        description="Painel de controle visual para filas do AgentCoordinator, chaves de cache semântico e circuit breaker.",
        category="Bancos & RAG",
        icon="🔴",
        downloads="2.1M",
        rating=4.87,
        upstream_id="joeferner.redis-commander",
        repository_url="https://github.com/joeferner/redis-commander",
        features=[
            "Monitoramento de filas BLPOP de agentes",
            "Estatísticas de taxa de acerto do cache semântico",
            "Inspeção de chaves e TTL em tempo real",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.minio-storage-explorer",
        name="MinIO & S3 Object Storage Explorer",
        publisher="minio",
        version="2.2.0",
        description="Navegador visual de buckets, documentos PDF, planilhas Excel (Calamine) e arquivos brutos do RAG.",
        category="Bancos & RAG",
        icon="🪣",
        downloads="880K",
        rating=4.90,
        upstream_id="minio.minio-vscode",
        repository_url="https://github.com/minio/minio",
        features=[
            "Preview de PDFs e planilhas integrados",
            "Upload com sanitização de caminhos anti-traversal",
            "Geração de URLs assinadas seguras",
        ],
    ),
    # ── SUÍTE 4: SEGURANÇA, GOVERNANÇA & AUDITORIA ─────────────────────────────
    ExtensionDefinition(
        id="eltanix.sast-security-scanner",
        name="SAST Security Scanner (Semgrep & Bandit)",
        publisher="semgrep",
        version="1.85.0",
        description="Análise estática contínua de código para barrar vulnerabilidades (SQLi, XSS, SSRF, Hardcoded Secrets) antes do commit.",
        category="Segurança & Auditoria",
        icon="🔒",
        downloads="1.4M",
        rating=4.97,
        upstream_id="Semgrep.semgrep",
        repository_url="https://github.com/semgrep/semgrep",
        features=[
            "Regras de segurança OWASP Top 10",
            "Varredura em Python, TypeScript, Go e Rust",
            "Auditoria automática de diffs do agente",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.dependency-cve-auditor",
        name="Dependency & License Auditor (Pip-Audit / AuditJS)",
        publisher="safety",
        version="2.4.0",
        description="Detecção contínua de CVEs em dependências instaladas e auditoria de conformidade de licenças de software.",
        category="Segurança & Auditoria",
        icon="🛡️",
        downloads="620K",
        rating=4.86,
        upstream_id="trailofbits.pip-audit",
        repository_url="https://github.com/pypa/pip-audit",
        features=[
            "Base de dados de vulnerabilidades OSV/PyPI/NPM",
            "Alertas de severidade crítica e alta",
            "Relatórios de compatibilidade de licenças (GPL, MIT, Apache)",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.token-cost-profiler",
        name="Token Cost & Latency Profiler",
        publisher="eltanix",
        version="2.1.0",
        description="Gráficos de telemetria de consumo de tokens, custo em USD por modelo e replay passo a passo do Flight Recorder.",
        category="Segurança & Auditoria",
        icon="💰",
        downloads="190K",
        rating=4.93,
        upstream_id="eltanix.flight-recorder",
        repository_url="https://github.com/LeonardoFSR75/Eltanix-Coder-IDE",
        features=[
            "Visualização de custos por modelo e sessão",
            "Replay cronológico de tool-calls",
            "Alertas de limite de orçamento (BudgetGuard)",
        ],
    ),
    # ── SUÍTE 5: TESTES, APIS & VERIFICAÇÃO E2E ─────────────────────────────────
    ExtensionDefinition(
        id="eltanix.playwright-visual-studio",
        name="Playwright Visual E2E Studio",
        publisher="ms-playwright",
        version="1.48.0",
        description="Gravador e executor de testes ponta a ponta com comparação de screenshots integrado ao navegador interno.",
        category="APIs & Testes",
        icon="🎭",
        downloads="4.8M",
        rating=4.96,
        upstream_id="ms-playwright.playwright",
        repository_url="https://github.com/microsoft/playwright",
        features=[
            "Execução visual com captura de tela",
            "Emulação de dispositivos móveis e desktop",
            "Relatórios de regressão visual",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.bruno-thunder-client",
        name="Bruno & Thunder Client API Runner",
        publisher="usebruno",
        version="1.30.0",
        description="Cliente visual de requisições REST/GraphQL integrado na IDE com suporte a coleções versionáveis em Git.",
        category="APIs & Testes",
        icon="⚡",
        downloads="3.2M",
        rating=4.94,
        upstream_id="usebruno.bruno",
        repository_url="https://github.com/usebruno/bruno",
        features=[
            "Coleções de requisições armazenadas no repositório",
            "Validação de contratos de resposta e schemas JSON",
            "Variáveis de ambiente isoladas",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.coverage-heatmap-viewer",
        name="Coverage Heatmap & Mutation Testing",
        publisher="coverage",
        version="1.6.0",
        description="Destaque visual direto no Monaco Editor mostrando linhas cobertas e não cobertas por testes automatizados.",
        category="APIs & Testes",
        icon="🧪",
        downloads="740K",
        rating=4.88,
        upstream_id="ryanluker.vscode-coverage-gutters",
        repository_url="https://github.com/ryanluker/vscode-coverage-gutters",
        features=[
            "Integração com coverage.py e vitest/lcov",
            "Gutter indicators verde/vermelho em tempo real",
            "Cálculo de percentual de cobertura por módulo",
        ],
    ),
    # ── SUÍTE 6: ARQUITETURA & SEGUNDO CÉREBRO (GRAPHYFY & OBSIDIAN) ────────────
    ExtensionDefinition(
        id="eltanix.graphify-3d-canvas",
        name="Graphify 3D Live Canvas",
        publisher="eltanix",
        version="2.4.0",
        description="Visualizador de grafo de dependências e comunidades acoplado ao editor que se atualiza conforme arquivos são editados.",
        category="Segundo Cérebro & Arquitetura",
        icon="🕸️",
        downloads="210K",
        rating=4.99,
        upstream_id="eltanix.graphify",
        repository_url="https://github.com/LeonardoFSR75/Eltanix-Coder-IDE",
        features=[
            "Visualização 2D/3D com física de clustering",
            "Navegação multi-hop e blast radius",
            "Sincronização com o cofre do Obsidian",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.adr-architecture-assistant",
        name="ADR Architecture Assistant",
        publisher="eltanix",
        version="1.5.0",
        description="Assistente guiado para redigir, validar e catalogar Decisões Arquiteturais com templates padronizados.",
        category="Segundo Cérebro & Arquitetura",
        icon="📑",
        downloads="140K",
        rating=4.92,
        upstream_id="eltanix.adr-tools",
        repository_url="https://github.com/LeonardoFSR75/Eltanix-Coder-IDE",
        features=[
            "Geração de ADRs com numeração automática",
            "Exportação para o índice de MOC do Obsidian",
            "Análise de impacto em componentes do grafo",
        ],
    ),
    ExtensionDefinition(
        id="eltanix.git-smart-blame",
        name="Git Smart Blame & Co-Change Matrix",
        publisher="eltanix",
        version="2.0.0",
        description="Análise preditiva de acoplamento temporal e histórico semântico de commits por autor e símbolo.",
        category="Segundo Cérebro & Arquitetura",
        icon="🐙",
        downloads="560K",
        rating=4.95,
        upstream_id="eltanix.git-intelligence",
        repository_url="https://github.com/LeonardoFSR75/Eltanix-Coder-IDE",
        features=[
            "Detecção de co-change (arquivos que mudam juntos)",
            "Blame contextual com autor e PR associado",
            "Mapeamento de hotspots de churn de código",
        ],
    ),
    # ── EXTENSÕES TRADICIONAIS LSP & LINGUAGENS (MANTIDAS & ATUALIZADAS) ────────
    ExtensionDefinition(
        id="meta.pyrefly",
        name="Pyrefly - Python Language Server",
        publisher="meta",
        version="0.2.1",
        description="Python autocomplete, typechecking & high-performance static analysis by Meta.",
        category="LSP & Linguagens",
        icon="🦟",
        downloads="600K",
        rating=4.90,
        upstream_id="meta.pyrefly",
    ),
    ExtensionDefinition(
        id="ms-python.python",
        name="Python",
        publisher="ms-python",
        version="2026.2.0",
        description="Python language support with extension hooks, formatting, linting & refactoring.",
        category="LSP & Linguagens",
        icon="🐍",
        downloads="110M",
        rating=4.85,
        upstream_id="ms-python.python",
    ),
    ExtensionDefinition(
        id="ms-python.debugpy",
        name="Python Debugger",
        publisher="ms-python",
        version="2026.2.0",
        description="Python Debugger extension using debugpy & Eltanix Coder IDE container executor.",
        category="LSP & Linguagens",
        icon="🐞",
        downloads="38M",
        rating=4.89,
        upstream_id="ms-python.debugpy",
    ),
    ExtensionDefinition(
        id="vue.volar",
        name="Vue.js Language Features (Volar)",
        publisher="vue",
        version="2.2.4",
        description="Vue 3 Composition API, Single File Components (.vue), template typechecking & Volar LSP.",
        category="LSP & Linguagens",
        icon="💚",
        downloads="7.5M",
        rating=4.93,
        upstream_id="vue.volar",
    ),
    ExtensionDefinition(
        id="svelte.svelte-vscode",
        name="Svelte & SvelteKit",
        publisher="svelte",
        version="108.5.0",
        description="Svelte 5 Runes, SvelteKit routing, reactive state autocomplete & Svelte LSP.",
        category="LSP & Linguagens",
        icon="🧡",
        downloads="1.8M",
        rating=4.95,
        upstream_id="svelte.svelte-vscode",
    ),
    ExtensionDefinition(
        id="tailwindcss.vscode-tailwindcss",
        name="Tailwind CSS IntelliSense",
        publisher="tailwindcss",
        version="0.14.3",
        description="Advanced class autocomplete, CSS directive linting, variant preview & color picker.",
        category="Frontend & Visual",
        icon="🌊",
        downloads="14M",
        rating=4.97,
        upstream_id="bradlc.vscode-tailwindcss",
    ),
    ExtensionDefinition(
        id="eamodio.gitlens",
        name="GitLens — Git supercharged",
        publisher="eamodio",
        version="2026.2.0",
        description="Autoria de código linha por linha (blame), histórico de commits e comparação visual de branches.",
        category="Produtividade",
        icon="🔍",
        downloads="32M",
        rating=4.92,
        upstream_id="eamodio.gitlens",
    ),
    ExtensionDefinition(
        id="usernamehw.errorlens",
        name="Error Lens",
        publisher="usernamehw",
        version="3.21.0",
        description="Exibe mensagens de erro, warnings e diagnósticos do LSP diretamente inline nas linhas de código.",
        category="Produtividade",
        icon="🔍",
        downloads="6.1M",
        rating=4.98,
        upstream_id="usernamehw.errorlens",
    ),
]
